<?xml version="1.0" encoding="utf-8"?>
<Database Name="Beans_DB_v5" Class="VolunteerDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WALKERS\SQLEXPRESS;Initial Catalog=Beans_DB_v5;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Beans_DB_v5ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Entity" Member="Entities">
    <Type Name="Entity">
      <Column Name="Entity_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Entity_Organization_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entity_Contact_FName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Entity_Contact_MName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entity_Contact_LName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Entity_Address1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entity_Address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entity_City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entity_State" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entity_ZipCode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Entity_Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Entity_Phone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Entity_Type" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Entity_Support_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Entity_Volunteer" Member="Volunteers" ThisKey="Entity_ID" OtherKey="Entity_ID" Type="Volunteer" />
    </Type>
  </Table>
  <Table Name="dbo.Volunteer" Member="Volunteers">
    <Type Name="Volunteer">
      <Column Name="Entity_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Shift_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Clock_In" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="Clock_Out" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="Volunteers_Scheduled" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Volunteers_Worked" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Community_Service" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Volunteer_Comments" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="is_client" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Entity_Volunteer" Member="Entity" ThisKey="Entity_ID" OtherKey="Entity_ID" Type="Entity" IsForeignKey="true" />
      <Association Name="Shift_Volunteer" Member="Shift" ThisKey="Shift_ID" OtherKey="Shift_ID" Type="Shift" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Shift" Member="Shifts">
    <Type Name="Shift">
      <Column Name="Shift_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Shift_Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Shift_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Shift_Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Shift_Volunteer" Member="Volunteers" ThisKey="Shift_ID" OtherKey="Shift_ID" Type="Volunteer" />
    </Type>
  </Table>
</Database>